<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>buding.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="buding.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NPOI" Version="2.8.0" />
    <PackageReference Include="OpenAI" Version="2.10.0" />
    <PackageReference Include="PdfPig" Version="0.1.14" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.8" />
    <PackageReference Include="Telegram.Bot" Version="22.10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="botconfig.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ValidUsers\users.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Users\" />
  </ItemGroup>

</Project>